<a href="https://colab.research.google.com/github/YogeshParihar1311/fake_news/blob/main/Fake_News.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from statsmodels.stats.outliers_influence import variance_inflation_factor
# from autoviz.classify_method import data_cleaning_suggestions ,data_suggestions

# from pycaret  import regression
from sklearn.model_selection import cross_val_score

In [ ]:
from google.colab import files

files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"yogeshparihar1311","key":"41646bae978e8cfc336f2cbe53f584d0"}'}

In [ ]:
! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

In [ ]:
 ! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets download ruchi798/source-based-news-classification

  0% 0.00/2.97M [00:00<?, ?B/s]
100% 2.97M/2.97M [00:00<00:00, 34.4MB/s]


In [ ]:
! unzip source-based-news-classification.zip

Archive:  source-based-news-classification.zip
  inflating: news_articles.csv       


In [ ]:
df = pd.read_csv("news_articles.csv",encoding='cp1252')

In [ ]:
df.shape

(2096, 12)

In [ ]:
df.head()

author                      published  \
0     Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1  reasoning with facts  2016-10-29T08:47:11.259+03:00   
2     Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                Fed Up  2016-11-01T05:22:00.000+02:00   
4                Fed Up  2016-11-01T21:56:00.000+02:00   

                                               title  \
0  muslims busted they stole millions in govt ben...   
1  re why did attorney general loretta lynch plea...   
2  breaking weiner cooperating with fbi on hillar...   
3  pin drop speech by father of daughter kidnappe...   
4  fantastic trumps  point plan to reform healthc...   

                                                text language  \
0  print they should pay all the back all the mon...  english   
1  why did attorney general loretta lynch plead t...  english   
2  red state  \nfox news sunday reported this mor...  english   
3  email kayla mueller was a prisoner and torture...  english   
4  email healthcare reform to make america great ...  english   

              site_url                                       main_img_url  \
0  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
1  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
2  100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
3  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
4  100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   

   type label                            title_without_stopwords  \
0  bias  Real        muslims busted stole millions govt benefits   
1  bias  Real         attorney general loretta lynch plead fifth   
2  bias  Real  breaking weiner cooperating fbi hillary email ...   
3  bias  Real  pin drop speech father daughter kidnapped kill...   
4  bias  Real  fantastic trumps point plan reform healthcare ...   

                              text_without_stopwords  hasImage  
0  print pay back money plus interest entire fami...       1.0  
1  attorney general loretta lynch plead fifth bar...       1.0  
2  red state fox news sunday reported morning ant...       1.0  
3  email kayla mueller prisoner tortured isis cha...       1.0  
4  email healthcare reform make america great sin...       1.0

In [ ]:
df = df[['author','language','site_url','type','label','title_without_stopwords','text_without_stopwords']]

In [ ]:
df.head()

author language             site_url  type label  \
0     Barracuda Brigade  english  100percentfedup.com  bias  Real   
1  reasoning with facts  english  100percentfedup.com  bias  Real   
2     Barracuda Brigade  english  100percentfedup.com  bias  Real   
3                Fed Up  english  100percentfedup.com  bias  Real   
4                Fed Up  english  100percentfedup.com  bias  Real   

                             title_without_stopwords  \
0        muslims busted stole millions govt benefits   
1         attorney general loretta lynch plead fifth   
2  breaking weiner cooperating fbi hillary email ...   
3  pin drop speech father daughter kidnapped kill...   
4  fantastic trumps point plan reform healthcare ...   

                              text_without_stopwords  
0  print pay back money plus interest entire fami...  
1  attorney general loretta lynch plead fifth bar...  
2  red state fox news sunday reported morning ant...  
3  email kayla mueller prisoner tortured isis cha...  
4  email healthcare reform make america great sin...

In [ ]:
df['language'].value_counts(normalize=True)

english    0.962768
german     0.034368
ignore     0.001432
french     0.000955
spanish    0.000477
Name: language, dtype: float64

In [ ]:
df = df[df['language']=='english']

In [ ]:
df.drop('language',axis=1,inplace=True)

In [ ]:
df.head()

author             site_url  type label  \
0     Barracuda Brigade  100percentfedup.com  bias  Real   
1  reasoning with facts  100percentfedup.com  bias  Real   
2     Barracuda Brigade  100percentfedup.com  bias  Real   
3                Fed Up  100percentfedup.com  bias  Real   
4                Fed Up  100percentfedup.com  bias  Real   

                             title_without_stopwords  \
0        muslims busted stole millions govt benefits   
1         attorney general loretta lynch plead fifth   
2  breaking weiner cooperating fbi hillary email ...   
3  pin drop speech father daughter kidnapped kill...   
4  fantastic trumps point plan reform healthcare ...   

                              text_without_stopwords  
0  print pay back money plus interest entire fami...  
1  attorney general loretta lynch plead fifth bar...  
2  red state fox news sunday reported morning ant...  
3  email kayla mueller prisoner tortured isis cha...  
4  email healthcare reform make america great sin...

In [ ]:
df['text'] = df['author'] + ' ' + df['site_url'] + ' ' + df['type'] + ' ' + df['title_without_stopwords'] + ' ' + df['text_without_stopwords']

In [ ]:
df.head()

author             site_url  type label  \
0     Barracuda Brigade  100percentfedup.com  bias  Real   
1  reasoning with facts  100percentfedup.com  bias  Real   
2     Barracuda Brigade  100percentfedup.com  bias  Real   
3                Fed Up  100percentfedup.com  bias  Real   
4                Fed Up  100percentfedup.com  bias  Real   

                             title_without_stopwords  \
0        muslims busted stole millions govt benefits   
1         attorney general loretta lynch plead fifth   
2  breaking weiner cooperating fbi hillary email ...   
3  pin drop speech father daughter kidnapped kill...   
4  fantastic trumps point plan reform healthcare ...   

                              text_without_stopwords  \
0  print pay back money plus interest entire fami...   
1  attorney general loretta lynch plead fifth bar...   
2  red state fox news sunday reported morning ant...   
3  email kayla mueller prisoner tortured isis cha...   
4  email healthcare reform make america great sin...   

                                                text  
0  Barracuda Brigade 100percentfedup.com bias mus...  
1  reasoning with facts 100percentfedup.com bias ...  
2  Barracuda Brigade 100percentfedup.com bias bre...  
3  Fed Up 100percentfedup.com bias pin drop speec...  
4  Fed Up 100percentfedup.com bias fantastic trum...

In [ ]:
df = df[['text','label']]

In [ ]:
df.head()

text label
0  Barracuda Brigade 100percentfedup.com bias mus...  Real
1  reasoning with facts 100percentfedup.com bias ...  Real
2  Barracuda Brigade 100percentfedup.com bias bre...  Real
3  Fed Up 100percentfedup.com bias pin drop speec...  Real
4  Fed Up 100percentfedup.com bias fantastic trum...  Real

In [ ]:
df['text'][0]

'Barracuda Brigade 100percentfedup.com bias muslims busted stole millions govt benefits print pay back money plus interest entire family everyone came need deported asap take two years bust go another group stealing government taxpayers group somalis stole four million government benefits months weve reported numerous cases like one muslim refugeesimmigrants commit fraud scamming systemits way control related'

In [ ]:
df.isnull().sum()/df.shape[0]*100

text     2.478929
label    0.000000
dtype: float64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()/df.shape[0]*100

text     0.0
label    0.0
dtype: float64

In [ ]:
df.duplicated().sum()

35

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# removing html tags
import re
def remove_tags(text):
    cleaned_txt = re.sub(re.compile('<.*?>'),'',text)
    return cleaned_txt

In [ ]:
# removing urls
def remove_urls(text):
    pattern = re.sub(re.compile(r'https?://\S+|www.\S+'),'',text)
    return pattern

In [ ]:
# remove punctuation
import string
exclude = string.punctuation
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

In [ ]:
# remove chat words
chat_words = {
    "AFAIK":"As Far As I Know",
"AFK":"Away From Keyboard",
"ASAP":"As Soon As Possible",
"ATK":"At The Keyboard",
"ATM":"At The Moment",
"A3":"Anytime, Anywhere, Anyplace",
"BAK":"Back At Keyboard",
"BBL":"Be Back Later",
"BBS":"Be Back Soon",
"BFN":"Bye For Now",
"B4N":"Bye For Now",
"BRB":"Be Right Back",
"BRT":"Be Right There",
"BTW":"By The Way",
"B4":"Before",
"B4N":"Bye For Now",
"CU":"See You",
"CUL8R":"See You Later",
"CYA":"See You",
"FAQ":"Frequently Asked Questions",
"FC":"Fingers Crossed",
"FWIW":"For What It's Worth",
"FYI":"For Your Information",
"GAL":"Get A Life",
"GG":"Good Game",
"GN":"Good Night",
"GMTA":"Great Minds Think Alike",
"GR8":"Great!",
"G9":"Genius",
"IC":"I See",
"ICQ":"I Seek you",
"ILU":"I Love You",
"IMHO":"In My Honest/Humble Opinion",
"IMO":"In My Opinion",
"IOW":"In Other Words",
"IRL":"In Real Life",
"KISS":"Keep It Simple, Stupid",
"LDR":"Long Distance Relationship",
"LMAO":"Laugh My A.. Off",
"LOL":"Laughing Out Loud",
"LTNS":"Long Time No See",
"L8R":"Later",
"MTE":"My Thoughts Exactly",
"M8":"Mate",
"NRN":"No Reply Necessary",
"OIC":"Oh I See",
"PITA":"Pain In The A..",
"PRT":"Party",
"PRW":"Parents Are Watching",
"QPSA":"Que Pasa",
"ROFL":"Rolling On The Floor Laughing",
"ROFLOL":"Rolling On The Floor Laughing Out Loud",
"ROTFLMAO":"Rolling On The Floor Laughing My A.. Off",
"SK8":"Skate",
"STATS":"Your sex and age",
"ASL":"Age, Sex, Location",
"THX":"Thank You",
"TTFN":"Ta-Ta For Now!",
"TTYL":"Talk To You Later",
"U":"You",
"U2":"You Too",
"U4E":"Yours For Ever",
"WB":"Welcome Back",
"WTF":"What The F...",
"WTG":"Way To Go!",
"WUF":"Where Are You From?",
"W8":"Wait...",
"7K":"Sick:-D Laugher",
}

In [ ]:
chat_words = []
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [ ]:
# spelling correction
from textblob import TextBlob
def spell_correction(text):
    textblob = TextBlob(text)
    return textblob.correct().string

In [ ]:
! pip install emoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for emoji: filename=emoji-2.2.0-py3-none-any.whl size=234926 sha256=9a6ec2c3867bcf7e2a7186fbe4c31ad999c89de3453bc634935f22db771d988e
  Stored in directory: /root/.cache/pip/wheels/9a/b8/0f/f580817231cbf59f6ade9fd132ff60ada1de9f7dc85521f857
Successfully built emoji


In [ ]:
# replace emoji
import emoji
def replace_emoji(text):
    return emoji.demojize(text)

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
# remove stop words
from nltk.corpus import stopwords
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return ' '.join(x)

In [ ]:
def transform_text(text):
    txt = remove_tags(text)
    txt1 = remove_urls(txt)
    txt2 = remove_punc(txt1)
    txt3 = chat_conversion(txt2)
    txt4 = spell_correction(txt3)
    txt5 = replace_emoji(txt4)
    txt6 = remove_stopwords(txt5)
    return txt6.lower()

In [ ]:
transform_text(df['text'][0])

'barracuda brigade 100percentfedupcom bias muslin dusted stole millions got benefits print pay back money plus interest entire family everyone came need deported sap take two years bust go another group stealing government taxpayers group somalis stole four million government benefits months  reported numerous cases like one muslin refugeesimmigrants commit fraud slamming systems way control related'

In [ ]:
df['text'] = df['text'].str.lower()

In [ ]:
df.head()

text label  num_char
0  barracuda brigade 100percentfedup.com bias mus...  Real       411
1  reasoning with facts 100percentfedup.com bias ...  Real      1373
2  barracuda brigade 100percentfedup.com bias bre...  Real      1057
3  fed up 100percentfedup.com bias pin drop speec...  Real       319
4  fed up 100percentfedup.com bias fantastic trum...  Real      1637

In [ ]:
df['num_char'] = df['text'].apply(len)

In [ ]:
df.head()

text label  num_char
0  barracuda brigade 100percentfedup.com bias mus...  Real       411
1  reasoning with facts 100percentfedup.com bias ...  Real      1373
2  barracuda brigade 100percentfedup.com bias bre...  Real      1057
3  fed up 100percentfedup.com bias pin drop speec...  Real       319
4  fed up 100percentfedup.com bias fantastic trum...  Real      1637

In [ ]:
df['num_char'].sort_values(ascending=False)

1288    22692
1816    22304
36      21841
58      21422
80      20757
        ...  
138        60
1927       58
1896       55
1913       52
92         43
Name: num_char, Length: 1932, dtype: int64

In [ ]:
# df['transformed_text'] = df['text'].apply(transform_text)

In [ ]:
df.head()

text label  num_char
0  barracuda brigade 100percentfedup.com bias mus...  Real       411
1  reasoning with facts 100percentfedup.com bias ...  Real      1373
2  barracuda brigade 100percentfedup.com bias bre...  Real      1057
3  fed up 100percentfedup.com bias pin drop speec...  Real       319
4  fed up 100percentfedup.com bias fantastic trum...  Real      1637

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['target'] = le.fit_transform(df['label'])

In [ ]:
df.head()

text label  num_char  target
0  barracuda brigade 100percentfedup.com bias mus...  Real       411       1
1  reasoning with facts 100percentfedup.com bias ...  Real      1373       1
2  barracuda brigade 100percentfedup.com bias bre...  Real      1057       1
3  fed up 100percentfedup.com bias pin drop speec...  Real       319       1
4  fed up 100percentfedup.com bias fantastic trum...  Real      1637       1

In [ ]:
df['target'].value_counts()

0    1182
1     750
Name: target, dtype: int64

In [ ]:
X = df['text']
y = df['target']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB,BernoulliNB
nb = MultinomialNB()
gnb = GaussianNB()
bnb = BernoulliNB()

In [ ]:
nb.fit(X_train_tfidf,y_train)
y_pred = nb.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.6847545219638242
********************************************************************************
[[236   0]
 [122  29]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.66      1.00      0.79       236
           1       1.00      0.19      0.32       151

    accuracy                           0.68       387
   macro avg       0.83      0.60      0.56       387
weighted avg       0.79      0.68      0.61       387



In [ ]:
gnb.fit(X_train_tfidf,y_train)
y_pred = gnb.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.7596899224806202
********************************************************************************
[[198  38]
 [ 55  96]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.78      0.84      0.81       236
           1       0.72      0.64      0.67       151

    accuracy                           0.76       387
   macro avg       0.75      0.74      0.74       387
weighted avg       0.76      0.76      0.76       387



In [ ]:
bnb.fit(X_train_tfidf,y_train)
y_pred = bnb.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.7028423772609819
********************************************************************************
[[212  24]
 [ 91  60]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.70      0.90      0.79       236
           1       0.71      0.40      0.51       151

    accuracy                           0.70       387
   macro avg       0.71      0.65      0.65       387
weighted avg       0.71      0.70      0.68       387



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [ ]:
rfc.fit(X_train_tfidf,y_train)
y_pred = rfc.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.9483204134366925
********************************************************************************
[[233   3]
 [ 17 134]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       236
           1       0.98      0.89      0.93       151

    accuracy                           0.95       387
   macro avg       0.96      0.94      0.94       387
weighted avg       0.95      0.95      0.95       387



In [ ]:
from xgboost import XGBClassifier
xgbc = XGBClassifier()

In [ ]:
xgbc.fit(X_train_tfidf,y_train)
y_pred = xgbc.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.9819121447028424
********************************************************************************
[[233   3]
 [  4 147]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       236
           1       0.98      0.97      0.98       151

    accuracy                           0.98       387
   macro avg       0.98      0.98      0.98       387
weighted avg       0.98      0.98      0.98       387



In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier()

In [ ]:
etc.fit(X_train_tfidf,y_train)
y_pred = etc.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.9121447028423773
********************************************************************************
[[231   5]
 [ 29 122]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.89      0.98      0.93       236
           1       0.96      0.81      0.88       151

    accuracy                           0.91       387
   macro avg       0.92      0.89      0.90       387
weighted avg       0.92      0.91      0.91       387



In [ ]:
from lightgbm import LGBMClassifier
lgbmc = LGBMClassifier()

In [ ]:
lgbmc.fit(X_train_tfidf,y_train)
y_pred = lgbmc.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))
print(accuracy_score(y_train,lgbmc.predict(X_train_tfidf)))
print('*'*80)
print(confusion_matrix(y_test,y_pred))
print('*'*80)
print(classification_report(y_test,y_pred))

0.9922480620155039
1.0
********************************************************************************
[[235   1]
 [  2 149]]
********************************************************************************
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       236
           1       0.99      0.99      0.99       151

    accuracy                           0.99       387
   macro avg       0.99      0.99      0.99       387
weighted avg       0.99      0.99      0.99       387



In [ ]:
from sklearn.model_selection import cross_val_score
cvs = cross_val_score(lgbmc,X_train_tfidf,y_train,cv=5)

In [ ]:
np.mean(cvs)

0.9889967637540453